export interface Recipe {
  id: string
  name: string
  description: string
  difficulty: "Easy" | "Medium" | "Hard"
  cookTime: number
  servings: number
  calories: number
  protein: number
  carbs?: number
  fat?: number
  ingredients: Array<{ name: string; amount: string; category?: string }>
  steps: string[]
  dietary: string[]
  substitutions?: Record<string, string[]>
}

const recipes: Recipe[] = [
  {
    id: "1",
    name: "Classic Margherita Pasta",
    description: "Fresh tomato-based pasta with basil and mozzarella",
    difficulty: "Easy",
    cookTime: 20,
    servings: 2,
    calories: 450,
    protein: 14,
    carbs: 62,
    fat: 15,
    ingredients: [
      { name: "Pasta", amount: "400g", category: "grains" },
      { name: "Tomatoes", amount: "4", category: "vegetables" },
      { name: "Garlic", amount: "2 cloves", category: "aromatics" },
      { name: "Fresh Basil", amount: "1 bunch", category: "herbs" },
      { name: "Mozzarella", amount: "200g", category: "dairy" },
      { name: "Olive Oil", amount: "3 tbsp", category: "oils" },
      { name: "Salt", amount: "to taste", category: "seasonings" },
    ],
    steps: [
      "Cook pasta according to package directions.",
      "Dice tomatoes and mince garlic.",
      "Heat olive oil and sauté garlic until fragrant.",
      "Add tomatoes and simmer for 10 minutes.",
      "Season with salt and add basil.",
      "Toss pasta with sauce and top with mozzarella.",
    ],
    dietary: ["Vegetarian"],
    substitutions: {
      Mozzarella: ["Parmesan", "Ricotta", "Feta"],
      "Fresh Basil": ["Oregano", "Parsley"],
    },
  },
  {
    id: "2",
    name: "Grilled Vegetable Stir-Fry",
    description: "Colorful mix of seasonal vegetables with ginger-garlic sauce",
    difficulty: "Easy",
    cookTime: 15,
    servings: 2,
    calories: 280,
    protein: 8,
    carbs: 35,
    fat: 12,
    ingredients: [
      { name: "Broccoli", amount: "200g", category: "vegetables" },
      { name: "Bell Peppers", amount: "2", category: "vegetables" },
      { name: "Carrots", amount: "2", category: "vegetables" },
      { name: "Garlic", amount: "3 cloves", category: "aromatics" },
      { name: "Ginger", amount: "1 tbsp", category: "aromatics" },
      { name: "Soy Sauce", amount: "2 tbsp", category: "condiments" },
      { name: "Sesame Oil", amount: "2 tbsp", category: "oils" },
    ],
    steps: [
      "Prepare vegetables by cutting into uniform sizes.",
      "Heat sesame oil in a wok or large skillet.",
      "Add garlic and ginger, stir-fry for 30 seconds.",
      "Add harder vegetables first (carrots, broccoli).",
      "Add softer vegetables after 2 minutes.",
      "Pour in soy sauce and toss everything together.",
      "Cook for 3-5 minutes until vegetables are tender-crisp.",
    ],
    dietary: ["Vegetarian", "Vegan", "Gluten-Free"],
    substitutions: {
      "Sesame Oil": ["Vegetable Oil", "Coconut Oil"],
      "Soy Sauce": ["Tamari", "Coconut Aminos"],
    },
  },
  {
    id: "3",
    name: "Chicken Caesar Wrap",
    description: "Grilled chicken breast with crispy vegetables in a soft tortilla",
    difficulty: "Easy",
    cookTime: 25,
    servings: 1,
    calories: 520,
    protein: 38,
    carbs: 45,
    fat: 18,
    ingredients: [
      { name: "Chicken Breast", amount: "200g", category: "proteins" },
      { name: "Flour Tortilla", amount: "1", category: "grains" },
      { name: "Romaine Lettuce", amount: "1 cup", category: "vegetables" },
      { name: "Parmesan Cheese", amount: "2 tbsp", category: "dairy" },
      { name: "Caesar Dressing", amount: "3 tbsp", category: "condiments" },
      { name: "Cherry Tomatoes", amount: "5", category: "vegetables" },
      { name: "Olive Oil", amount: "1 tbsp", category: "oils" },
    ],
    steps: [
      "Season chicken breast with salt and pepper.",
      "Heat olive oil in a skillet over medium-high heat.",
      "Grill chicken for 6-7 minutes on each side.",
      "Slice cooked chicken into strips.",
      "Warm tortilla in a dry pan for 30 seconds each side.",
      "Layer tortilla with lettuce, chicken, tomatoes, and cheese.",
      "Drizzle with caesar dressing and roll up.",
    ],
    dietary: [],
    substitutions: {
      "Chicken Breast": ["Turkey", "Tofu"],
      "Flour Tortilla": ["Whole Wheat Tortilla", "Corn Tortilla"],
    },
  },
  {
    id: "4",
    name: "Buddha Bowl",
    description: "Nutritious bowl with quinoa, roasted vegetables, and tahini dressing",
    difficulty: "Medium",
    cookTime: 35,
    servings: 2,
    calories: 420,
    protein: 16,
    carbs: 52,
    fat: 14,
    ingredients: [
      { name: "Quinoa", amount: "1 cup", category: "grains" },
      { name: "Sweet Potato", amount: "1 large", category: "vegetables" },
      { name: "Chickpeas", amount: "1 can", category: "legumes" },
      { name: "Kale", amount: "2 cups", category: "vegetables" },
      { name: "Avocado", amount: "1", category: "fruits" },
      { name: "Tahini", amount: "2 tbsp", category: "condiments" },
      { name: "Lemon Juice", amount: "2 tbsp", category: "citrus" },
      { name: "Olive Oil", amount: "3 tbsp", category: "oils" },
    ],
    steps: [
      "Cook quinoa according to package directions.",
      "Cube sweet potato and roast at 200°C for 25 minutes.",
      "Drain and rinse chickpeas, toss with olive oil and paprika.",
      "Roast chickpeas at 200°C for 15 minutes until crispy.",
      "Massage kale with olive oil to soften.",
      "Mix tahini with lemon juice for dressing.",
      "Assemble bowls with quinoa, roasted vegetables, kale, and avocado.",
    ],
    dietary: ["Vegetarian", "Vegan"],
    substitutions: {
      Quinoa: ["Brown Rice", "Millet"],
      Chickpeas: ["Lentils", "Black Beans"],
      Tahini: ["Almond Butter", "Peanut Butter"],
    },
  },
  {
    id: "5",
    name: "Spaghetti Carbonara",
    description: "Creamy Italian pasta with bacon and parmesan",
    difficulty: "Medium",
    cookTime: 30,
    servings: 2,
    calories: 580,
    protein: 24,
    carbs: 58,
    fat: 24,
    ingredients: [
      { name: "Spaghetti", amount: "400g", category: "grains" },
      { name: "Eggs", amount: "3", category: "proteins" },
      { name: "Bacon", amount: "200g", category: "proteins" },
      { name: "Parmesan Cheese", amount: "100g", category: "dairy" },
      { name: "Black Pepper", amount: "to taste", category: "seasonings" },
      { name: "Salt", amount: "to taste", category: "seasonings" },
    ],
    steps: [
      "Cook spaghetti according to package directions.",
      "Fry bacon until crispy, then chop into pieces.",
      "Whisk eggs with grated parmesan and black pepper.",
      "Drain pasta, reserving 1 cup pasta water.",
      "Toss hot pasta with bacon.",
      "Remove from heat and quickly add egg mixture, tossing constantly.",
      "Add pasta water as needed for creamy consistency.",
    ],
    dietary: [],
    substitutions: {
      Bacon: ["Pancetta", "Prosciutto", "Mushrooms (vegetarian)"],
      Eggs: ["Cashew Cream (vegan)"],
    },
  },
  {
    id: "6",
    name: "Thai Green Curry",
    description: "Aromatic curry with coconut milk and fresh herbs",
    difficulty: "Hard",
    cookTime: 40,
    servings: 3,
    calories: 380,
    protein: 22,
    carbs: 28,
    fat: 18,
    ingredients: [
      { name: "Chicken", amount: "500g", category: "proteins" },
      { name: "Coconut Milk", amount: "400ml", category: "dairy" },
      { name: "Green Curry Paste", amount: "3 tbsp", category: "condiments" },
      { name: "Thai Basil", amount: "1 cup", category: "herbs" },
      { name: "Bamboo Shoots", amount: "200g", category: "vegetables" },
      { name: "Red Chili", amount: "2", category: "vegetables" },
      { name: "Fish Sauce", amount: "2 tbsp", category: "condiments" },
      { name: "Lime Juice", amount: "1 tbsp", category: "citrus" },
    ],
    steps: [
      "Heat 1 tbsp coconut milk in a wok.",
      "Add curry paste and fry for 1 minute.",
      "Add diced chicken and cook for 3 minutes.",
      "Pour in remaining coconut milk and simmer for 15 minutes.",
      "Add bamboo shoots and chili slices.",
      "Season with fish sauce and lime juice.",
      "Top with fresh Thai basil before serving.",
    ],
    dietary: [],
    substitutions: {
      Chicken: ["Shrimp", "Tofu"],
      "Fish Sauce": ["Soy Sauce", "Tamari"],
    },
  },
  {
    id: "7",
    name: "Quinoa Power Salad",
    description: "Protein-packed salad with vegetables, nuts, and vinaigrette",
    difficulty: "Easy",
    cookTime: 20,
    servings: 2,
    calories: 350,
    protein: 14,
    carbs: 38,
    fat: 16,
    ingredients: [
      { name: "Quinoa", amount: "1 cup", category: "grains" },
      { name: "Mixed Greens", amount: "2 cups", category: "vegetables" },
      { name: "Cherry Tomatoes", amount: "1 cup", category: "vegetables" },
      { name: "Cucumber", amount: "1", category: "vegetables" },
      { name: "Almonds", amount: "100g", category: "nuts" },
      { name: "Feta Cheese", amount: "100g", category: "dairy" },
      { name: "Olive Oil", amount: "3 tbsp", category: "oils" },
      { name: "Balsamic Vinegar", amount: "2 tbsp", category: "condiments" },
    ],
    steps: [
      "Cook quinoa according to package directions.",
      "Let quinoa cool to room temperature.",
      "Chop vegetables into bite-sized pieces.",
      "Toast almonds in a dry pan for 2 minutes.",
      "Toss greens with olive oil and balsamic vinegar.",
      "Layer greens with cooled quinoa and vegetables.",
      "Top with almonds and crumbled feta cheese.",
    ],
    dietary: ["Vegetarian", "Gluten-Free"],
    substitutions: {
      Almonds: ["Walnuts", "Sunflower Seeds"],
      "Feta Cheese": ["Goat Cheese", "Parmesan"],
    },
  },
  {
    id: "8",
    name: "Baked Salmon Filet",
    description: "Herb-crusted salmon with lemon and garlic",
    difficulty: "Medium",
    cookTime: 25,
    servings: 2,
    calories: 480,
    protein: 42,
    carbs: 5,
    fat: 28,
    ingredients: [
      { name: "Salmon Fillets", amount: "2 x 200g", category: "proteins" },
      { name: "Olive Oil", amount: "2 tbsp", category: "oils" },
      { name: "Fresh Herbs", amount: "2 tbsp", category: "herbs" },
      { name: "Garlic", amount: "2 cloves", category: "aromatics" },
      { name: "Lemon", amount: "1", category: "citrus" },
      { name: "Salt", amount: "to taste", category: "seasonings" },
      { name: "Black Pepper", amount: "to taste", category: "seasonings" },
    ],
    steps: [
      "Preheat oven to 200°C.",
      "Place salmon on parchment paper.",
      "Brush with olive oil and season with salt and pepper.",
      "Sprinkle fresh herbs and minced garlic on top.",
      "Slice lemon and place on salmon.",
      "Bake for 15-18 minutes until salmon is cooked through.",
      "Serve immediately with lemon wedges.",
    ],
    dietary: ["Gluten-Free", "Dairy-Free"],
    substitutions: {
      Salmon: ["Trout", "Mackerel", "Halibut"],
    },
  },
  {
    id: "9",
    name: "Vegetable Soup",
    description: "Hearty vegetable soup with beans and aromatic broth",
    difficulty: "Easy",
    cookTime: 30,
    servings: 3,
    calories: 220,
    protein: 9,
    carbs: 28,
    fat: 6,
    ingredients: [
      { name: "Vegetable Broth", amount: "1 liter", category: "liquids" },
      { name: "Carrots", amount: "3", category: "vegetables" },
      { name: "Celery", amount: "2 stalks", category: "vegetables" },
      { name: "Onion", amount: "1", category: "aromatics" },
      { name: "Canned Beans", amount: "1 can", category: "legumes" },
      { name: "Tomatoes", amount: "2", category: "vegetables" },
      { name: "Garlic", amount: "2 cloves", category: "aromatics" },
      { name: "Olive Oil", amount: "2 tbsp", category: "oils" },
    ],
    steps: [
      "Heat olive oil in a large pot.",
      "Sauté diced onion, carrots, and celery for 5 minutes.",
      "Add minced garlic and cook for 1 minute.",
      "Pour in vegetable broth and bring to a boil.",
      "Add diced tomatoes and canned beans.",
      "Simmer for 20 minutes until vegetables are tender.",
      "Season with salt and pepper to taste.",
    ],
    dietary: ["Vegetarian", "Vegan", "Gluten-Free"],
    substitutions: {
      "Canned Beans": ["Lentils", "Chickpeas"],
    },
  },
  {
    id: "10",
    name: "Beef Tacos",
    description: "Seasoned ground beef tacos with fresh toppings",
    difficulty: "Easy",
    cookTime: 20,
    servings: 2,
    calories: 420,
    protein: 28,
    carbs: 35,
    fat: 16,
    ingredients: [
      { name: "Ground Beef", amount: "300g", category: "proteins" },
      { name: "Taco Shells", amount: "8", category: "grains" },
      { name: "Lettuce", amount: "2 cups", category: "vegetables" },
      { name: "Tomato", amount: "2", category: "vegetables" },
      { name: "Cheddar Cheese", amount: "100g", category: "dairy" },
      { name: "Sour Cream", amount: "100ml", category: "dairy" },
      { name: "Salsa", amount: "100ml", category: "condiments" },
      { name: "Taco Seasoning", amount: "1 packet", category: "seasonings" },
    ],
    steps: [
      "Brown ground beef in a skillet over medium-high heat.",
      "Drain excess fat from the meat.",
      "Add taco seasoning and water according to packet directions.",
      "Simmer for 5 minutes.",
      "Warm taco shells in the oven.",
      "Chop lettuce and tomato.",
      "Assemble tacos with meat, lettuce, tomato, cheese, and toppings.",
    ],
    dietary: [],
    substitutions: {
      "Ground Beef": ["Ground Turkey", "Plant-Based Meat"],
      "Taco Shells": ["Corn Tortillas", "Lettuce Wraps"],
    },
  },
  {
    id: "11",
    name: "Caprese Salad",
    description: "Italian salad with tomato, mozzarella, and basil",
    difficulty: "Easy",
    cookTime: 5,
    servings: 2,
    calories: 280,
    protein: 12,
    carbs: 8,
    fat: 22,
    ingredients: [
      { name: "Tomatoes", amount: "3 large", category: "vegetables" },
      { name: "Fresh Mozzarella", amount: "250g", category: "dairy" },
      { name: "Fresh Basil", amount: "1 bunch", category: "herbs" },
      { name: "Olive Oil", amount: "3 tbsp", category: "oils" },
      { name: "Balsamic Vinegar", amount: "1 tbsp", category: "condiments" },
      { name: "Salt", amount: "to taste", category: "seasonings" },
      { name: "Black Pepper", amount: "to taste", category: "seasonings" },
    ],
    steps: [
      "Slice tomatoes into thick rounds.",
      "Slice fresh mozzarella to match tomato size.",
      "Alternate tomato and mozzarella on a plate.",
      "Tear fresh basil and scatter on top.",
      "Drizzle with olive oil and balsamic vinegar.",
      "Season with salt and pepper.",
      "Serve immediately.",
    ],
    dietary: ["Vegetarian"],
    substitutions: {
      "Fresh Mozzarella": ["Ricotta", "Burrata"],
      "Fresh Basil": ["Oregano"],
    },
  },
  {
    id: "12",
    name: "Asian Noodle Bowl",
    description: "Stir-fried noodles with vegetables and peanut sauce",
    difficulty: "Medium",
    cookTime: 25,
    servings: 2,
    calories: 450,
    protein: 16,
    carbs: 52,
    fat: 18,
    ingredients: [
      { name: "Rice Noodles", amount: "300g", category: "grains" },
      { name: "Bell Peppers", amount: "2", category: "vegetables" },
      { name: "Carrots", amount: "2", category: "vegetables" },
      { name: "Peanut Butter", amount: "3 tbsp", category: "condiments" },
      { name: "Soy Sauce", amount: "2 tbsp", category: "condiments" },
      { name: "Lime Juice", amount: "2 tbsp", category: "citrus" },
      { name: "Garlic", amount: "3 cloves", category: "aromatics" },
      { name: "Sesame Oil", amount: "2 tbsp", category: "oils" },
    ],
    steps: [
      "Cook rice noodles according to package directions.",
      "Prepare vegetables by slicing into thin strips.",
      "Make peanut sauce by mixing peanut butter, soy sauce, lime juice, and garlic.",
      "Heat sesame oil in a wok.",
      "Stir-fry vegetables for 3-4 minutes.",
      "Add cooked noodles and peanut sauce.",
      "Toss everything together and serve.",
    ],
    dietary: ["Vegan"],
    substitutions: {
      "Peanut Butter": ["Almond Butter", "Tahini"],
      "Rice Noodles": ["Wheat Noodles"],
    },
  },
  {
    id: "13",
    name: "Grilled Vegetable Skewers",
    description: "Marinated vegetables grilled on skewers",
    difficulty: "Easy",
    cookTime: 20,
    servings: 2,
    calories: 240,
    protein: 6,
    carbs: 28,
    fat: 12,
    ingredients: [
      { name: "Zucchini", amount: "2 medium", category: "vegetables" },
      { name: "Red Onion", amount: "1 large", category: "aromatics" },
      { name: "Bell Peppers", amount: "2", category: "vegetables" },
      { name: "Cherry Tomatoes", amount: "16", category: "vegetables" },
      { name: "Olive Oil", amount: "3 tbsp", category: "oils" },
      { name: "Balsamic Vinegar", amount: "2 tbsp", category: "condiments" },
      { name: "Garlic", amount: "3 cloves", category: "aromatics" },
      { name: "Fresh Herbs", amount: "2 tbsp", category: "herbs" },
    ],
    steps: [
      "Soak wooden skewers in water for 30 minutes.",
      "Cut vegetables into uniform pieces.",
      "Make marinade with olive oil, balsamic vinegar, garlic, and herbs.",
      "Thread vegetables onto skewers.",
      "Brush with marinade.",
      "Grill for 10-12 minutes, turning occasionally.",
      "Serve with extra marinade for dipping.",
    ],
    dietary: ["Vegetarian", "Vegan", "Gluten-Free"],
    substitutions: {
      "Cherry Tomatoes": ["Pearl Onions"],
    },
  },
  {
    id: "14",
    name: "Lentil Curry",
    description: "Warming Indian curry with red lentils and spices",
    difficulty: "Medium",
    cookTime: 40,
    servings: 3,
    calories: 320,
    protein: 18,
    carbs: 45,
    fat: 8,
    ingredients: [
      { name: "Red Lentils", amount: "1 cup", category: "legumes" },
      { name: "Coconut Milk", amount: "400ml", category: "dairy" },
      { name: "Onion", amount: "2", category: "aromatics" },
      { name: "Garlic", amount: "4 cloves", category: "aromatics" },
      { name: "Ginger", amount: "2 tbsp", category: "aromatics" },
      { name: "Curry Powder", amount: "2 tbsp", category: "seasonings" },
      { name: "Turmeric", amount: "1 tsp", category: "seasonings" },
      { name: "Coconut Oil", amount: "2 tbsp", category: "oils" },
    ],
    steps: [
      "Heat coconut oil in a pot.",
      "Sauté diced onion, garlic, and ginger for 3 minutes.",
      "Add curry powder and turmeric, cook for 1 minute.",
      "Add red lentils and stir.",
      "Pour in coconut milk and 2 cups water.",
      "Bring to boil, then simmer for 25-30 minutes.",
      "Serve over rice.",
    ],
    dietary: ["Vegan", "Gluten-Free"],
    substitutions: {
      "Red Lentils": ["Yellow Lentils", "Chickpeas"],
    },
  },
  {
    id: "15",
    name: "Shrimp Scampi",
    description: "Garlic butter shrimp with white wine sauce",
    difficulty: "Medium",
    cookTime: 20,
    servings: 2,
    calories: 380,
    protein: 35,
    carbs: 8,
    fat: 22,
    ingredients: [
      { name: "Shrimp", amount: "400g", category: "proteins" },
      { name: "Butter", amount: "4 tbsp", category: "dairy" },
      { name: "Garlic", amount: "6 cloves", category: "aromatics" },
      { name: "White Wine", amount: "150ml", category: "liquids" },
      { name: "Lemon Juice", amount: "2 tbsp", category: "citrus" },
      { name: "Pasta", amount: "400g", category: "grains" },
      { name: "Fresh Parsley", amount: "2 tbsp", category: "herbs" },
      { name: "Salt", amount: "to taste", category: "seasonings" },
    ],
    steps: [
      "Cook pasta according to package directions.",
      "Melt butter in a large skillet over medium heat.",
      "Add minced garlic and cook for 1 minute.",
      "Add shrimp and cook until pink, about 3-4 minutes per side.",
      "Pour in white wine and lemon juice.",
      "Simmer for 2 minutes.",
      "Toss with pasta and garnish with fresh parsley.",
    ],
    dietary: ["Gluten-Free (with GF pasta)"],
    substitutions: {
      Shrimp: ["Chicken", "Scallops"],
      "White Wine": ["Vegetable Broth"],
    },
  },
  {
    id: "16",
    name: "Black Bean Burgers",
    description: "Homemade plant-based burgers with black beans",
    difficulty: "Medium",
    cookTime: 30,
    servings: 4,
    calories: 340,
    protein: 14,
    carbs: 42,
    fat: 12,
    ingredients: [
      { name: "Black Beans", amount: "2 cans", category: "legumes" },
      { name: "Breadcrumbs", amount: "100g", category: "grains" },
      { name: "Onion", amount: "1", category: "aromatics" },
      { name: "Garlic", amount: "2 cloves", category: "aromatics" },
      { name: "Cumin", amount: "1 tsp", category: "seasonings" },
      { name: "Chili Powder", amount: "1 tsp", category: "seasonings" },
      { name: "Olive Oil", amount: "2 tbsp", category: "oils" },
      { name: "Burger Buns", amount: "4", category: "grains" },
    ],
    steps: [
      "Drain and rinse black beans.",
      "Pulse beans in a food processor until roughly mashed.",
      "Dice onion and garlic finely.",
      "Mix beans with breadcrumbs, onion, garlic, cumin, and chili powder.",
      "Form into 4 patties.",
      "Heat olive oil in a skillet.",
      "Cook patties for 4-5 minutes per side until golden.",
    ],
    dietary: ["Vegan", "Vegetarian"],
    substitutions: {
      "Black Beans": ["Chickpeas", "Lentils"],
      Breadcrumbs: ["Oat Flour"],
    },
  },
  {
    id: "17",
    name: "Caprese Chicken",
    description: "Chicken topped with tomato, mozzarella, and basil",
    difficulty: "Medium",
    cookTime: 30,
    servings: 2,
    calories: 480,
    protein: 42,
    carbs: 8,
    fat: 28,
    ingredients: [
      { name: "Chicken Breasts", amount: "2 x 200g", category: "proteins" },
      { name: "Fresh Mozzarella", amount: "200g", category: "dairy" },
      { name: "Tomatoes", amount: "2 large", category: "vegetables" },
      { name: "Fresh Basil", amount: "1 bunch", category: "herbs" },
      { name: "Olive Oil", amount: "3 tbsp", category: "oils" },
      { name: "Balsamic Vinegar", amount: "2 tbsp", category: "condiments" },
      { name: "Garlic", amount: "2 cloves", category: "aromatics" },
      { name: "Salt", amount: "to taste", category: "seasonings" },
    ],
    steps: [
      "Preheat oven to 200°C.",
      "Season chicken with salt and pepper.",
      "Sear chicken in olive oil for 3 minutes per side.",
      "Top each chicken with tomato slices and mozzarella.",
      "Drizzle with balsamic vinegar.",
      "Bake for 15 minutes until cheese melts.",
      "Top with fresh basil and serve.",
    ],
    dietary: ["Gluten-Free"],
    substitutions: {
      "Chicken Breasts": ["Turkey", "Pork"],
    },
  },
  {
    id: "18",
    name: "Mediterranean Hummus Bowl",
    description: "Creamy hummus with roasted vegetables and pita",
    difficulty: "Easy",
    cookTime: 15,
    servings: 2,
    calories: 380,
    protein: 12,
    carbs: 48,
    fat: 16,
    ingredients: [
      { name: "Chickpeas", amount: "1 can", category: "legumes" },
      { name: "Tahini", amount: "3 tbsp", category: "condiments" },
      { name: "Lemon Juice", amount: "3 tbsp", category: "citrus" },
      { name: "Garlic", amount: "3 cloves", category: "aromatics" },
      { name: "Olive Oil", amount: "3 tbsp", category: "oils" },
      { name: "Pita Bread", amount: "4 pieces", category: "grains" },
      { name: "Cucumber", amount: "1", category: "vegetables" },
      { name: "Tomatoes", amount: "2", category: "vegetables" },
    ],
    steps: [
      "Drain and rinse chickpeas.",
      "Blend chickpeas, tahini, lemon juice, garlic, and 2 tbsp olive oil.",
      "Transfer to serving bowl and create well in center.",
      "Drizzle with remaining olive oil.",
      "Serve with pita bread, cucumber, and tomato slices.",
    ],
    dietary: ["Vegan", "Vegetarian"],
    substitutions: {
      Tahini: ["Almond Butter"],
      "Pita Bread": ["Crackers"],
    },
  },
  {
    id: "19",
    name: "Miso Glazed Tofu",
    description: "Pan-seared tofu with miso glaze and vegetables",
    difficulty: "Medium",
    cookTime: 25,
    servings: 2,
    calories: 320,
    protein: 20,
    carbs: 18,
    fat: 18,
    ingredients: [
      { name: "Tofu", amount: "400g", category: "proteins" },
      { name: "Miso Paste", amount: "3 tbsp", category: "condiments" },
      { name: "Honey", amount: "2 tbsp", category: "condiments" },
      { name: "Soy Sauce", amount: "1 tbsp", category: "condiments" },
      { name: "Sesame Oil", amount: "2 tbsp", category: "oils" },
      { name: "Ginger", amount: "1 tbsp", category: "aromatics" },
      { name: "Garlic", amount: "2 cloves", category: "aromatics" },
      { name: "Scallions", amount: "3", category: "aromatics" },
    ],
    steps: [
      "Press tofu to remove excess moisture.",
      "Cut into thick slices.",
      "Mix miso paste, honey, soy sauce, and ginger.",
      "Heat sesame oil in a skillet.",
      "Pan-sear tofu for 3-4 minutes per side.",
      "Brush with miso glaze.",
      "Top with sliced scallions and serve.",
    ],
    dietary: ["Vegan", "Vegetarian", "Gluten-Free"],
    substitutions: {
      Tofu: ["Tempeh"],
      Honey: ["Agave"],
    },
  },
  {
    id: "20",
    name: "Mushroom Risotto",
    description: "Creamy rice with sautéed mushrooms and parmesan",
    difficulty: "Hard",
    cookTime: 40,
    servings: 3,
    calories: 420,
    protein: 14,
    carbs: 58,
    fat: 14,
    ingredients: [
      { name: "Arborio Rice", amount: "300g", category: "grains" },
      { name: "Mushrooms", amount: "300g", category: "vegetables" },
      { name: "Vegetable Broth", amount: "1 liter", category: "liquids" },
      { name: "White Wine", amount: "150ml", category: "liquids" },
      { name: "Onion", amount: "1", category: "aromatics" },
      { name: "Garlic", amount: "2 cloves", category: "aromatics" },
      { name: "Parmesan Cheese", amount: "100g", category: "dairy" },
      { name: "Butter", amount: "2 tbsp", category: "dairy" },
    ],
    steps: [
      "Heat broth in a separate pot and keep warm.",
      "Chop mushrooms and sauté in butter until golden.",
      "Remove mushrooms and set aside.",
      "Sauté diced onion and garlic.",
      "Add rice and stir for 2 minutes.",
      "Pour in white wine and stir until absorbed.",
      "Gradually add warm broth, one ladle at a time, stirring constantly for 20 minutes.",
      "Finish with mushrooms, parmesan, and butter.",
    ],
    dietary: ["Vegetarian"],
    substitutions: {
      Mushrooms: ["Asparagus"],
      Parmesan: ["Pecorino"],
    },
  },
  {
    id: "21",
    name: "Falafel Pita",
    description: "Crispy chickpea fritters in pita with tahini sauce",
    difficulty: "Medium",
    cookTime: 30,
    servings: 4,
    calories: 380,
    protein: 13,
    carbs: 42,
    fat: 16,
    ingredients: [
      { name: "Chickpeas", amount: "2 cans", category: "legumes" },
      { name: "Onion", amount: "1", category: "aromatics" },
      { name: "Garlic", amount: "4 cloves", category: "aromatics" },
      { name: "Cumin", amount: "1 tsp", category: "seasonings" },
      { name: "Coriander", amount: "1 tsp", category: "seasonings" },
      { name: "Pita Bread", amount: "4", category: "grains" },
      { name: "Tahini", amount: "3 tbsp", category: "condiments" },
      { name: "Olive Oil", amount: "3 tbsp", category: "oils" },
    ],
    steps: [
      "Drain chickpeas and pulse with onion, garlic, cumin, and coriander.",
      "Form into balls and flatten slightly.",
      "Heat olive oil in a skillet.",
      "Fry falafel for 3-4 minutes per side until golden.",
      "Warm pita bread.",
      "Mix tahini with water to make sauce.",
      "Stuff pita with falafel, lettuce, tomato, and tahini sauce.",
    ],
    dietary: ["Vegan", "Vegetarian"],
    substitutions: {
      Chickpeas: ["Fava Beans"],
    },
  },
  {
    id: "22",
    name: "Beef Stir-Fry Rice",
    description: "Tender beef with vegetables over jasmine rice",
    difficulty: "Medium",
    cookTime: 30,
    servings: 2,
    calories: 520,
    protein: 32,
    carbs: 48,
    fat: 16,
    ingredients: [
      { name: "Beef Sirloin", amount: "400g", category: "proteins" },
      { name: "Jasmine Rice", amount: "300g", category: "grains" },
      { name: "Bell Peppers", amount: "2", category: "vegetables" },
      { name: "Broccoli", amount: "200g", category: "vegetables" },
      { name: "Soy Sauce", amount: "3 tbsp", category: "condiments" },
      { name: "Garlic", amount: "4 cloves", category: "aromatics" },
      { name: "Ginger", amount: "1 tbsp", category: "aromatics" },
      { name: "Sesame Oil", amount: "2 tbsp", category: "oils" },
    ],
    steps: [
      "Cook jasmine rice according to package directions.",
      "Slice beef thinly against the grain.",
      "Heat sesame oil in a wok over high heat.",
      "Stir-fry beef until browned, then set aside.",
      "Add vegetables and stir-fry for 3-4 minutes.",
      "Return beef to wok, add soy sauce, garlic, and ginger.",
      "Serve over jasmine rice.",
    ],
    dietary: ["Gluten-Free (with tamari)"],
    substitutions: {
      "Beef Sirloin": ["Chicken", "Tofu"],
    },
  },
  {
    id: "23",
    name: "Eggplant Parmesan",
    description: "Breaded eggplant layers with marinara and cheese",
    difficulty: "Medium",
    cookTime: 45,
    servings: 3,
    calories: 380,
    protein: 16,
    carbs: 32,
    fat: 18,
    ingredients: [
      { name: "Eggplant", amount: "2 large", category: "vegetables" },
      { name: "Breadcrumbs", amount: "200g", category: "grains" },
      { name: "Marinara Sauce", amount: "500ml", category: "condiments" },
      { name: "Mozzarella", amount: "300g", category: "dairy" },
      { name: "Parmesan", amount: "100g", category: "dairy" },
      { name: "Eggs", amount: "2", category: "proteins" },
      { name: "Olive Oil", amount: "3 tbsp", category: "oils" },
      { name: "Fresh Basil", amount: "1 bunch", category: "herbs" },
    ],
    steps: [
      "Slice eggplant into rounds and salt lightly.",
      "Let sit for 15 minutes, then pat dry.",
      "Dip eggplant in beaten egg, then breadcrumbs.",
      "Fry in olive oil until golden on both sides.",
      "Layer eggplant, marinara, and mozzarella in a baking dish.",
      "Top with parmesan.",
      "Bake at 200°C for 20 minutes until cheese bubbles.",
    ],
    dietary: ["Vegetarian"],
    substitutions: {
      Eggplant: ["Zucchini"],
    },
  },
  {
    id: "24",
    name: "Korean Bibimbap",
    description: "Mixed rice bowl with vegetables, egg, and gochujang sauce",
    difficulty: "Medium",
    cookTime: 35,
    servings: 2,
    calories: 480,
    protein: 16,
    carbs: 58,
    fat: 18,
    ingredients: [
      { name: "Short-Grain Rice", amount: "300g", category: "grains" },
      { name: "Egg", amount: "2", category: "proteins" },
      { name: "Spinach", amount: "200g", category: "vegetables" },
      { name: "Carrots", amount: "2", category: "vegetables" },
      { name: "Zucchini", amount: "1", category: "vegetables" },
      { name: "Gochujang", amount: "3 tbsp", category: "condiments" },
      { name: "Sesame Oil", amount: "2 tbsp", category: "oils" },
      { name: "Garlic", amount: "3 cloves", category: "aromatics" },
    ],
    steps: [
      "Cook rice according to package directions.",
      "Blanch spinach and season with sesame oil and garlic.",
      "Julienne carrots and zucchini, sauté separately.",
      "Fry eggs sunny-side up.",
      "Divide rice into bowls and arrange vegetables on top.",
      "Top with fried egg.",
      "Mix gochujang with water and serve on the side.",
    ],
    dietary: ["Vegetarian"],
    substitutions: {
      Egg: ["Tofu"],
      "Short-Grain Rice": ["Brown Rice"],
    },
  },
  {
    id: "25",
    name: "Vegetable Fried Rice",
    description: "Day-old rice with scrambled eggs and mixed vegetables",
    difficulty: "Easy",
    cookTime: 20,
    servings: 2,
    calories: 350,
    protein: 14,
    carbs: 42,
    fat: 14,
    ingredients: [
      { name: "Cooked Rice", amount: "3 cups", category: "grains" },
      { name: "Eggs", amount: "2", category: "proteins" },
      { name: "Peas", amount: "200g", category: "vegetables" },
      { name: "Carrots", amount: "1", category: "vegetables" },
      { name: "Soy Sauce", amount: "2 tbsp", category: "condiments" },
      { name: "Sesame Oil", amount: "2 tbsp", category: "oils" },
      { name: "Garlic", amount: "2 cloves", category: "aromatics" },
      { name: "Scallions", amount: "2", category: "aromatics" },
    ],
    steps: [
      "Heat sesame oil in a wok or large skillet.",
      "Scramble eggs and set aside.",
      "Stir-fry diced carrots and garlic for 2 minutes.",
      "Add rice and break up clumps.",
      "Add peas and cooked eggs.",
      "Pour in soy sauce and toss well.",
      "Top with scallions and serve.",
    ],
    dietary: ["Vegetarian"],
    substitutions: {
      Eggs: ["Tofu"],
    },
  },
]

export class RecipeDatabase {
  static getRecipes(): Recipe[] {
    return recipes
  }

  static getRecipeById(id: string): Recipe | undefined {
    return recipes.find((r) => r.id === id)
  }

  static getAllIngredients(): string[] {
    const ingredients = new Set<string>()
    recipes.forEach((recipe) => {
      recipe.ingredients.forEach((ing) => {
        ingredients.add(ing.name)
      })
    })
    return Array.from(ingredients).sort()
  }

  static searchRecipes(query: string): Recipe[] {
    const lowerQuery = query.toLowerCase()
    return recipes.filter(
      (recipe) =>
        recipe.name.toLowerCase().includes(lowerQuery) ||
        recipe.description.toLowerCase().includes(lowerQuery) ||
        recipe.ingredients.some((ing) => ing.name.toLowerCase().includes(lowerQuery)),
    )
  }

  static getSubstitutions(ingredient: string): string[] {
    for (const recipe of recipes) {
      if (recipe.substitutions && recipe.substitutions[ingredient]) {
        return recipe.substitutions[ingredient]
      }
    }
    return []
  }

  static getIngredientsByCategory(category: string): string[] {
    const ingredients = new Set<string>()
    recipes.forEach((recipe) => {
      recipe.ingredients
        .filter((ing) => ing.category === category)
        .forEach((ing) => {
          ingredients.add(ing.name)
        })
    })
    return Array.from(ingredients).sort()
  }
}
